name = "Bucket: Zeus Terrain Editing";
dir = "@Bucket";
author = "Seb";
actionName = "Website";
action = "http://www.carpenoctem.co";
description = "Bucket: Zeus Terrain Editing";
tooltip = "Bucket: Zeus Terrain Editing";
tooltipOwned = "Bucket: Zeus Terrain Editing";
overview = "Bucket: Zeus Terrain Editing";
overviewText = "Bucket: Zeus Terrain Editing";
logoSmall	 = "logoSmall.paa";	    // Display next to the item added by the mod
logo		 = "logoSmall.paa";			// Logo displayed in the main menu
logoOver	 = "logoSmall.paa";	
