#define COMPONENT main
#include "\z\Bucket\addons\main\script_mod.hpp"

// #define DEBUG_MODE_FULL
// #define DISABLE_COMPILE_CACHE

#ifdef DEBUG_ENABLED_Bucket
    #define DEBUG_MODE_FULL
#endif
    #ifdef DEBUG_SETTINGS_OTHER
    #define DEBUG_SETTINGS DEBUG_SETTINGS_Bucket
#endif

#include "\z\Bucket\addons\main\script_macros.hpp"

#define IDD_TERRAIN_EDITOR 45100
#define IDC_SIZE_SLIDERTEXT 45101
#define IDC_SIZE_SLIDERWIDTH 45102
#define IDC_SIZE_SLIDERLENGTH 45103
#define IDC_SPEED_SLIDERTEXT 45104
#define IDC_SPEED_SLIDER 45105
#define IDC_ANGLE_SLIDERTEXT 45106
#define IDC_ANGLE_SLIDER 45107
#define IDC_SMOOTH_SLIDERTEXT 45108
#define IDC_SMOOTH_SLIDER 45109
#define IDC_RECTANGLE 45110
#define IDC_OBJECTS 45111
#define IDC_FLATTEN 45112
#define IDC_EXIT 45113
