PREP(drawBrush);
PREP(getUIParams);
PREP(initDisplay);
PREP(modifyTerrain);
PREP(terrainEditorLoop);
PREP(uiAngleSliderPosChanged);
PREP(uiSizeSliderPosChanged);
PREP(uiSmoothSliderPosChanged);
PREP(uiSpeedSliderPosChanged);
